// Generated by CoffeeScript 1.6.3
(function() {
  exports.MongoAdapter = require('./MongoAdapter');

  exports.configure = function(config) {
    return new exports.MongoAdapter(config);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
