// Generated by CoffeeScript 1.6.3
(function() {
  var SourcedAdapter;

  SourcedAdapter = exports;

  SourcedAdapter.MongoAdapter = require('./MongoAdapter');

  SourcedAdapter.configure = function(config) {
    return new exports.MongoAdapter(config);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
