// Generated by CoffeeScript 1.6.3
(function() {
  var MongoJS, MongoStorage, Sourced;

  Sourced = require('boco-sourced');

  MongoJS = require('mongojs');

  module.exports = MongoStorage = (function() {
    function MongoStorage(config) {
      if (config == null) {
        config = {};
      }
      this.connectionString = config.connectionString;
      this.revisionsCollectionName = config.revisionsCollectionName;
    }

    MongoStorage.prototype.getDatabase = function() {
      if (this.db != null) {
        return this.db;
      }
      return this.db = MongoJS(this.connectionString);
    };

    MongoStorage.prototype.getRevisionsCollection = function() {
      if (this.revisionsCollection != null) {
        return this.revisionsCollection;
      }
      return this.revisionsCollection = this.getDatabase().collection(this.revisionsCollectionName);
    };

    MongoStorage.prototype.storeRevision = function(revision, callback) {
      var collection;
      collection = this.getRevisionsCollection();
      return collection.insert(revision, function(error) {
        if (error == null) {
          return callback();
        }
        if (error.code !== 11000) {
          return callback(error);
        }
        return callback(new Sourced.RevisionConflict());
      });
    };

    MongoStorage.prototype.findRevisions = function(resourceType, resourceId, callback) {
      var collection, query;
      collection = this.getRevisionsCollection();
      query = {
        resourceType: resourceType,
        resourceId: resourceId
      };
      return collection.find(query).toArray(function(error, results) {
        return callback(error, results);
      });
    };

    return MongoStorage;

  })();

}).call(this);

/*
//@ sourceMappingURL=MongoAdapter.map
*/
