// Generated by CoffeeScript 1.6.3
(function() {
  var MongoAdapter;

  module.exports = MongoAdapter = (function() {
    function MongoAdapter(config) {
      if (config == null) {
        config = {};
      }
    }

    MongoAdapter.prototype.storeRevision = function(revision, callback) {};

    MongoAdapter.prototype.findRevisions = function(resourceType, resourceId, callback) {};

    return MongoAdapter;

  })();

}).call(this);

/*
//@ sourceMappingURL=MongoAdapter.map
*/
